// Liste exhaustive de langues supportées par Google Translate
export const LANGUAGES: { code: string; name: string; flag: string }[] = [
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "it", name: "Italiano", flag: "🇮🇹" },
  { code: "pt", name: "Português", flag: "🇵🇹" },
  { code: "nl", name: "Nederlands", flag: "🇳🇱" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
  { code: "pl", name: "Polski", flag: "🇵🇱" },
  { code: "ro", name: "Română", flag: "🇷🇴" },
  { code: "tr", name: "Türkçe", flag: "🇹🇷" },
  { code: "el", name: "Ελληνικά", flag: "🇬🇷" },
  { code: "sv", name: "Svenska", flag: "🇸🇪" },
  { code: "no", name: "Norsk", flag: "🇳🇴" },
  { code: "da", name: "Dansk", flag: "🇩🇰" },
  { code: "fi", name: "Suomi", flag: "🇫🇮" },
  { code: "cs", name: "Čeština", flag: "🇨🇿" },
  { code: "sk", name: "Slovenčina", flag: "🇸🇰" },
  { code: "hu", name: "Magyar", flag: "🇭🇺" },
  { code: "uk", name: "Українська", flag: "🇺🇦" },
  { code: "bg", name: "Български", flag: "🇧🇬" },
  { code: "hr", name: "Hrvatski", flag: "🇭🇷" },
  { code: "sr", name: "Српски", flag: "🇷🇸" },
  { code: "sl", name: "Slovenščina", flag: "🇸🇮" },
  { code: "ar", name: "العربية", flag: "🇸🇦" },
  { code: "he", name: "עברית", flag: "🇮🇱" },
  { code: "fa", name: "فارسی", flag: "🇮🇷" },
  { code: "ur", name: "اردو", flag: "🇵🇰" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "bn", name: "বাংলা", flag: "🇧🇩" },
  { code: "ta", name: "தமிழ்", flag: "🇱🇰" },
  { code: "te", name: "తెలుగు", flag: "🇮🇳" },
  { code: "ml", name: "മലയാളം", flag: "🇮🇳" },
  { code: "mr", name: "मराठी", flag: "🇮🇳" },
  { code: "gu", name: "ગુજરાતી", flag: "🇮🇳" },
  { code: "pa", name: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  { code: "ne", name: "नेपाली", flag: "🇳🇵" },
  { code: "si", name: "සිංහල", flag: "🇱🇰" },
  { code: "th", name: "ไทย", flag: "🇹🇭" },
  { code: "vi", name: "Tiếng Việt", flag: "🇻🇳" },
  { code: "id", name: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "ms", name: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "tl", name: "Filipino", flag: "🇵🇭" },
  { code: "zh-CN", name: "中文 (简体)", flag: "🇨🇳" },
  { code: "zh-TW", name: "中文 (繁體)", flag: "🇹🇼" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "mn", name: "Монгол", flag: "🇲🇳" },
  { code: "my", name: "မြန်မာ", flag: "🇲🇲" },
  { code: "km", name: "ខ្មែរ", flag: "🇰🇭" },
  { code: "lo", name: "ລາວ", flag: "🇱🇦" },
  { code: "ka", name: "ქართული", flag: "🇬🇪" },
  { code: "hy", name: "Հայերեն", flag: "🇦🇲" },
  { code: "az", name: "Azərbaycan", flag: "🇦🇿" },
  { code: "kk", name: "Қазақша", flag: "🇰🇿" },
  { code: "uz", name: "Oʻzbekcha", flag: "🇺🇿" },
  { code: "ky", name: "Кыргызча", flag: "🇰🇬" },
  { code: "tg", name: "Тоҷикӣ", flag: "🇹🇯" },
  { code: "ps", name: "پښتو", flag: "🇦🇫" },
  { code: "sw", name: "Kiswahili", flag: "🇰🇪" },
  { code: "am", name: "አማርኛ", flag: "🇪🇹" },
  { code: "ha", name: "Hausa", flag: "🇳🇬" },
  { code: "yo", name: "Yorùbá", flag: "🇳🇬" },
  { code: "ig", name: "Igbo", flag: "🇳🇬" },
  { code: "zu", name: "isiZulu", flag: "🇿🇦" },
  { code: "xh", name: "isiXhosa", flag: "🇿🇦" },
  { code: "af", name: "Afrikaans", flag: "🇿🇦" },
  { code: "so", name: "Soomaali", flag: "🇸🇴" },
  { code: "rw", name: "Kinyarwanda", flag: "🇷🇼" },
  { code: "mg", name: "Malagasy", flag: "🇲🇬" },
  { code: "ny", name: "Chichewa", flag: "🇲🇼" },
  { code: "sn", name: "Shona", flag: "🇿🇼" },
  { code: "st", name: "Sesotho", flag: "🇱🇸" },
  { code: "ca", name: "Català", flag: "🏴" },
  { code: "eu", name: "Euskara", flag: "🏴" },
  { code: "gl", name: "Galego", flag: "🏴" },
  { code: "cy", name: "Cymraeg", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { code: "ga", name: "Gaeilge", flag: "🇮🇪" },
  { code: "gd", name: "Gàidhlig", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { code: "is", name: "Íslenska", flag: "🇮🇸" },
  { code: "mt", name: "Malti", flag: "🇲🇹" },
  { code: "lb", name: "Lëtzebuergesch", flag: "🇱🇺" },
  { code: "et", name: "Eesti", flag: "🇪🇪" },
  { code: "lv", name: "Latviešu", flag: "🇱🇻" },
  { code: "lt", name: "Lietuvių", flag: "🇱🇹" },
  { code: "be", name: "Беларуская", flag: "🇧🇾" },
  { code: "mk", name: "Македонски", flag: "🇲🇰" },
  { code: "bs", name: "Bosanski", flag: "🇧🇦" },
  { code: "sq", name: "Shqip", flag: "🇦🇱" },
  { code: "eo", name: "Esperanto", flag: "🌐" },
  { code: "la", name: "Latina", flag: "🏛️" },
  { code: "yi", name: "ייִדיש", flag: "✡️" },
  { code: "haw", name: "ʻŌlelo Hawaiʻi", flag: "🌺" },
  { code: "mi", name: "Māori", flag: "🇳🇿" },
  { code: "sm", name: "Gagana Samoa", flag: "🇼🇸" },
  { code: "co", name: "Corsu", flag: "🏴" },
  { code: "fy", name: "Frysk", flag: "🏴" },
  { code: "su", name: "Basa Sunda", flag: "🇮🇩" },
  { code: "jw", name: "Basa Jawa", flag: "🇮🇩" },
  { code: "ku", name: "Kurdî", flag: "🏴" },
  { code: "sd", name: "سنڌي", flag: "🇵🇰" },
];

export const SOURCE_LANG = "fr";
